### ISSUE TITLE
🐛 [bug] - Observe Monitoring Dashboard Fails 

### ISSUE THREAD

**Issue by eformat** [rht-labs/tech-exercise#106]
### 📝 Description
In Eercise 4 as a normal user

https://rht-labs.com/tech-exercise/#/4-return-of-the-monitoring/1-enable-monitoring

Cannot see Dashboard - get forbidden

![Screenshot from 2022-01-18 15-29-08](https://user-images.githubusercontent.com/712608/149879920-18ef7c21-6317-4c18-9fd3-789d93f01412.png)

### 🧙‍♀️ Suggested solution
Could be this?

https://bugzilla.redhat.com/show_bug.cgi?id=2026414
https://github.com/openshift/console/pull/10548

**Comment by ckavili** [comment]
this seems to be working with OpenShift 4.10 🥳🥳🥳

**Comment by eformat** [comment]
@ckavili  well so it does !!
![yay2](https://user-images.githubusercontent.com/712608/154380331-7231a10b-2af3-49d6-9082-59e719935e10.gif)

![Screenshot from 2022-02-17 10-23-06](https://user-images.githubusercontent.com/712608/154380356-ca080b29-743f-4036-9c44-e507c092d67c.png)
