### ISSUE TITLE
👑 [exercise] - Code coverage and linting

### ISSUE THREAD

**Issue by ckavili** [rht-labs/tech-exercise#11]
### Quality Gates
* Module: Code coverage and linting

### 📝 Description
Introduce Code coverage and linting for front end and API (Jenkins & Tekton)

### 🥤 Additional Info 
Docs:
[Code coverage and linting - General Info](https://github.com/rht-labs/tech-exercise/blob/main/docs/3-revenge-of-the-automated-testing/4-code-coverage-linting.md)
[Jenkins](https://github.com/rht-labs/tech-exercise/blob/main/docs/3-revenge-of-the-automated-testing/4a-jenkins.md)
[Tekton](https://github.com/rht-labs/tech-exercise/blob/main/docs/3-revenge-of-the-automated-testing/4b-tekton.md)

### ✅ A/Cs
- [x] Big Picture Updated (if applicable)  
- [x] Facilitator notes updated (if applicable)
- [x] Exercise peer reviewed / tested with one other region member
- [x] Addition of new exercise does not affect previous exercise (maintain modularity)

**Comment by eformat** [comment]
LGTM
