### ISSUE TITLE
🐛 [bug] - Security Browser Warnings on initial password reset 

### ISSUE THREAD

**Issue by kattekrab** [rht-labs/tech-exercise#116]
### 📝 Description
When TL500 participants get the email with Login info, many of them can't proceed due to Browser Security Settings.  While there are ways to work around it, the user experience at this point causes unneccessary concern and confusion.

Chrome NET::ERR_CERT_AUTHORITY_INVALID
Firefox Error code: SEC_ERROR_UNKNOWN_ISSUER

### 🚶 Steps to reproduce
Find Login info:
Click link to https://ipa.apps.***.rht-labs.com/. (replace *** as per your server info)
See screenshots below of firefox and chrome.  
This will vary depending on user's specific browser config.

### 🧙‍♀️ Suggested solution
Can we automate set up of SSL certificates in lodestar to prevent this from happening?

![Screen Shot 2022-01-25 at 11 08 42 am](https://user-images.githubusercontent.com/172755/150886156-b1bfb7c1-6aaf-4c77-99e8-8b446f6621ee.png)

![Screen Shot 2022-01-25 at 11 07 04 am](https://user-images.githubusercontent.com/172755/150886169-23200788-2a79-4309-8b0b-5ef3ddbefaf2.png)

**Comment by eformat** [comment]
closing in favor of

https://github.com/rht-labs/enablement-framework/issues/84
