### ISSUE TITLE
👑 [exercise] - Image Security

### ISSUE THREAD

**Issue by ckavili** [rht-labs/tech-exercise#12]
### Quality Gates
* Module: Image Security

### 📝 Description
Add image security steps for front end and API (Jenkins & Tekton)

### 🥤 Additional Info 
Docs:
[Image Security - General Info](https://github.com/rht-labs/tech-exercise/blob/main/docs/3-revenge-of-the-automated-testing/3-image-security.md)
[Jenkins](https://github.com/rht-labs/tech-exercise/blob/main/docs/3-revenge-of-the-automated-testing/3a-jenkins.md)
[Tekton](https://github.com/rht-labs/tech-exercise/blob/main/docs/3-revenge-of-the-automated-testing/3b-tekton.md)

### ✅ A/Cs
- [ ] Big Picture Updated (if applicable)  
- [ ] Facilitator notes updated (if applicable)
- [ ] Exercise peer reviewed / tested with one other region member
- [ ] Addition of new exercise does not affect previous exercise (maintain modularity)

**Comment by eformat** [comment]
@ckavili @springdo i propose we delete this section as it is all covered under StackRox section

or we could split the StackRox section up more ... StackRox/ACS is the right tool for this job

**Comment by springdo** [comment]
Ok - let's close this as won't fix
