### ISSUE TITLE
🐛 [bug] - Docsify pagination skips next steps, jumps straight to next section.

### ISSUE THREAD

**Issue by kattekrab** [rht-labs/tech-exercise#129]
### 📝 Description
Section pagination is confusing.
"Next" at the end of the first page of section jumps straight to the next section, instead of to the first step in that section.

For example.  
The Manual Menace links directly to Attack of the Pipelines, when it should link to The Basics.

### 🚶 Steps to reproduce
Go to https://rht-labs.com/tech-exercise/#/1-the-manual-menace/README
Scroll to bottom of the page.
Click "2. Attack of the Pipelines"

### 🧙‍♀️ Suggested solution
This has something to do with docsify pagination, but I'm unsure how to fix it.

Ideally Manual Menace intro should link to [The Basics](https://rht-labs.com/tech-exercise/#/1-the-manual-menace/1-the-basics), which then links to argocd... and so on, rather than skipping to the next section. 

![image](https://user-images.githubusercontent.com/172755/152617651-e03807f2-46f3-41b2-b292-e4537db15737.png)

**Comment by ckavili** [comment]
thanks for the heads up @kattekrab , fixed :)
