### ISSUE TITLE
🧑‍🏫 [facilitator] - create a box for <TEAM_NAME> / <CLUSTER_DOMAIN> to automatically fill the correct into for attendees

### ISSUE THREAD

**Issue by springdo** [rht-labs/tech-exercise#13]
Here's a thought....

there are sections of the docs that have yaml like this:
```yaml
source: "https://gitlab-ce.apps.<CLUSTER_DOMAIN>/<TEAM_NAME>/tech-exercise.git"
team: <TEAM_NAME>
```

we have the attendees do a find and replace, but Im just thinking, we could probs write a docsify plugin or something along those lines to parse the page before it's rendered and replace these with the values used by a team. Im thinking, something lightweight with just two text boxes or something that you fill in when you open the docs and can set the values in local storage so refreshes etc are still good. I think this will help some of the typo issues we have seen historically and also mean we don't maintain forks of the repo for each team. What do you guys think?
@philipdouble - i see that docsify has lifecycle hooks perhaps we can use these to our advantage? https://docsify.js.org/#/write-a-plugin  

FYI @eformat / @philipdouble / @Rileyi  / @ckavili

**Comment by springdo** [comment]
![image](https://user-images.githubusercontent.com/6122439/128911815-81dbf993-77e2-465c-89a5-32a1b94965ee.png)

@eformat / @philipdouble / @Rileyi / @ckavili - what do yous think?

**Comment by springdo** [comment]
Can we mark this as done for now?

**Comment by eformat** [comment]
@springdo - i'd say YES ! 🧽
