### ISSUE TITLE
🐛 [bug] - Slides tech exercise iii 7

### ISSUE THREAD

**Issue by kattekrab** [rht-labs/tech-exercise#133]
### 📝 Description
The final word "good" is out of alignment with the rest of the sentence.
See screenshot

### 🚶 Steps to reproduce
go to https://rht-labs.com/tech-exercise/slides/content/?name=tech-exercise-iii#/7

### 🧙‍♀️ Suggested solution
Adding a line break before the image should sort this out.

Bug filed on behalf of Nicholas Wong (dunno his github id tho)

![Screen Shot 2022-02-05 at 11 25 09 am](https://user-images.githubusercontent.com/172755/152620522-4c099823-b900-4c4f-97b6-098d8683e411.png)

**Comment by kattekrab** [comment]
in the file
https://github.com/rht-labs/tech-exercise/blob/main/docs/slides/content/tech-exercise-iii.md

Someone added this inline comment raising the exact same issue:
"

The markdown is making this a bit tricky - so I wonder if explicitly adding an HTML p tag around the intro sentence would do the trick, but I don't know how to test that, so I've deleted the PR I did.

**Comment by ckavili** [comment]
it seems alright now, thanks @kattekrab 
https://rht-labs.com/tech-exercise/slides/content/?name=tech-exercise-iii#/7

I also removed the Tech Edit :)
