### ISSUE TITLE
👑 [exercise] - User workload monitoring

### ISSUE THREAD

**Issue by springdo** [rht-labs/tech-exercise#14]
### Observability
* Module: User Workload Monitoring

### 📝 Description
Learners should extend their pet-battle infra with the `grafana` chart. This is done for each team as it is namespaced. Probs need one for `test` & `stage`. Then via argocd override, we can enable ServiceMonitor. Teams should discuss what are important measures eg api response time or uptime etc and build a simple query for their dashboard to show this.

### 🥤 Additional Info 
grafana from pb-infra [here](https://github.com/petbattle/pet-battle-infra/tree/main/grafana)
service monitor on chart is [here](https://github.com/rht-labs/pet-battle-api/blob/main/chart/templates/service-monitor.yaml)

### ✅ A/Cs
- [x] Big Picture Updated (if applicable)  
- [x] Facilitator notes updated (if applicable)
- [x] Exercise peer reviewed / tested with one other region member
- [x] Addition of new exercise does not affect previous exercise (maintain modularity)

**Comment by ckavili** [comment]
@springdo and I are tackling this one 🚀

**Comment by rmarting** [comment]
@springdo @ckavili Proposed some changes after my review.

**Comment by eformat** [comment]
LGTM
