### ISSUE TITLE
🐛 [bug] - Extra ` in copy for exercise 1

### ISSUE THREAD

**Issue by mcanoy** [rht-labs/tech-exercise#149]
### 📝 Description
Looks like this - (look after labs.com)

```
echo export CLUSTER_DOMAIN="apps.tl500-2.dev-1.rht-labs.com`" | tee -a ~/.bashrc -a ~/.zshrc
```

### 🚶 Steps to reproduce
https://rht-labs.com/tech-exercise/#/1-the-manual-menace/1-the-basics Step 5. Copy and paste into codeready

### 🧙‍♀️ Suggested solution
remove `

```
echo export CLUSTER_DOMAIN="apps.tl500-2.dev-1.rht-labs.com" | tee -a ~/.bashrc -a ~/.zshrc
``

**Comment by eformat** [comment]
hey @mcanoy you sure ? i just did this OK.

![Screenshot from 2022-03-07 15-46-25](https://user-images.githubusercontent.com/712608/156975297-131af8ec-2c69-4c39-afe2-18e832517961.png)

what's in your browser local storage where the docs are ?

![Screenshot from 2022-03-07 15-48-14](https://user-images.githubusercontent.com/712608/156975452-3106604f-a017-4f29-a9ca-a07ebf328e95.png)

**Comment by mcanoy** [comment]
you're right. I added the tick
