### ISSUE TITLE
🐛 [bug] - Removed extra jenkins-agents in The Manual Manace's Big Picture

### ISSUE THREAD

**Issue by rmarting** [rht-labs/tech-exercise#167]
### 📝 Description

The current [Big Picture](https://rht-labs.com/tech-exercise/#/1-the-manual-menace/README) in **The Manual Manace** lab includes the following _jenkins-agents_:

- Python
- Cosign

Both _jenkins-agents_ are not deployed/used in this lab, as they are part of the **Revenge of the Automated Testing** lab.

### 🧙‍♀️ Suggested solution

Update the Big Picture to remove both _jenkins-agents_ from the picture.

**Comment by rmarting** [comment]
Could we go ahead and close it? A PR was merged related to this issue. @springdo Housekeeping?

**Comment by eformat** [comment]
LGTM !
