### ISSUE TITLE
🐛 [bug] - Gaps in the pipeline described in Attack of the Pipelines's Big Picture

### ISSUE THREAD

**Issue by rmarting** [rht-labs/tech-exercise#168]
### 📝 Description

The current [Big Picture](https://rht-labs.com/tech-exercise/#/2-attack-of-the-pipelines/README) in **Attack of the Pipelines** lab includes the following stages:

- System Test
- Promote

Both stages are not used in this lab, as they are part of the **Revenge of the Automated Testing** lab.

It also a _bug_ in the **deploy** stage, as the steps defined are:

- Get Package
- Helm Lint

but it should be only one step **Helm Package**

Also it could be great to add another extra tool in the CRW canvas, the kubeseal-cli as it will used to encrypt the secrets.

### 🧙‍♀️ Suggested solution

Update the Big Picture to remove these stages from the picture and add the extra developer tool (kubeseal-cli).

**Comment by rmarting** [comment]
Could we go ahead and close it? A PR was merged related to this issue. @springdo Housekeeping?

**Comment by eformat** [comment]
LGTM !
