### ISSUE TITLE
🐛 [bug] - Gaps in the Return of the Monitoring's Big Picture

### ISSUE THREAD

**Issue by rmarting** [rht-labs/tech-exercise#169]
### 📝 Description

The current [Big Picture](https://rht-labs.com/tech-exercise/#/4-return-of-the-monitoring/README) in **Returng of the Monitoring** lab is missing the following items:

- **Logging** namespace
- ElasticSearch and Kibana components inside of Logging namespace

### 🧙‍♀️ Suggested solution

Update the Big Picture to add the **logging** namespace and its items (ElasticSearch and Kibana), as they appears in the Big Picture in the [The Deployments Strike back](https://rht-labs.com/tech-exercise/#/5-the-deployments-strike-back/README) picture.

**Comment by rmarting** [comment]
Could we go ahead and close it? A PR was merged related to this issue. @springdo Housekeeping?

**Comment by eformat** [comment]
LGTM !
