### ISSUE TITLE
👑 [exercise] - Alerting

### ISSUE THREAD

**Issue by springdo** [rht-labs/tech-exercise#18]
### Observability
* Module: Alerting

### 📝 Description
Use `PrometheusRule` to fire alerts when specific events happen. 
As a team, come up with new metric to alert on... Extend the base alerts to include this new alert

### 🥤 Additional Info 
alerting for pet-battle stuff [here](https://github.com/petbattle/ubiquitous-journey/tree/main/applications/alerting/chart) 

### ✅ A/Cs
- [x] Big Picture Updated (if applicable)  
- [x] Facilitator notes updated (if applicable)
- [x] Exercise peer reviewed / tested with one other region member
- [x] Addition of new exercise does not affect previous exercise (maintain modularity)

**Comment by eformat** [comment]
LGTM
