### ISSUE TITLE
🐛 [bug] - Grafana dashboard is not working (Forbidden errors)

### ISSUE THREAD

**Issue by rmarting** [rht-labs/tech-exercise#181]
### 📝 Description

Following the instructions of the [Enabling monitoring](https://rht-labs.com/tech-exercise/#/4-return-of-the-monitoring/1-enable-monitoring) exercises, we found forbidden errors in the Grafana dashboard as the next screenshot shows:

![image](https://user-images.githubusercontent.com/8723668/176775906-f7bb4247-f31f-4738-95ab-ee66901fb577.png)

A sample request to the Grafana dashboard is:

```
https://grafana-route-biscuits-ci-cd.apps.sabadell-2.ls-eu.ole.redhat.com/api/datasources/proxy/1/api/v1/query_range?query=sum%20by%20(method)(http_server_requests_seconds_count%20%7Boutcome%3D%22CLIENT_ERROR%22%7D)&start=1656535920&end=1656622320&step=120
```

Got the following response 403 and the content is the OpenShift login form.

### 🚶 Steps to reproduce

Followed the instructions of this exercise, and login with the student user in Grafana.

### 🧙‍♀️ Suggested solution
... if applicable

**Comment by rmarting** [comment]
@springdo @ckavili Did you see this issue in your last enablements? I have different teams working on the same practice and all of then got the same issue (as I can reproduce it too). Ideas?

**Comment by eformat** [comment]
h i @rmarting - i think i know what this is (recent change may have broken this). i will check. for now, you can workaround by doing this in your *-ci-cd namespace

```
TOKEN=`oc serviceaccounts get-token grafana-serviceaccount`
oc patch grafanadatasource prometheus-grafanadatasource --type='json' -p='[{"op":"add","path":"/spec/datasources/0/secureJsonData/httpHeaderValue1","value":"Bearer '${TOKEN}'"}]'
```

i will revert/fix this up

**Comment by eformat** [comment]
this should fix it now.

https://github.com/petbattle/pet-battle-infra/commit/20172faa74fd812bad87bacd0e6b3f669aeb8ba6

if you Sync Grafana in your ArgoCD instances, the token should be inserted OK.

Check:

```
oc get grafanadatasource prometheus-grafanadatasource -o jsonpath="{.spec.datasources[0].secureJsonData.httpHeaderValue1}"
```

**Comment by rmarting** [comment]
Thanks a lot, @eformat !!!

Basically, ArgoCD applied your changes in our environments and now Grafana is working successfully!!!

**GitOps** works!!! :smile:

**Comment by eformat** [comment]
![bitmoji](https://sdk.bitmoji.com/render/panel/de982485-6268-48af-857b-4dfe491cf102-1f324690-f554-4139-ae97-7554cdb2ae7f-v1.png?transparent=1&palette=1&width=246)

Wahooo !! great !!
