### ISSUE TITLE
👑 [exercise] - Autoscaling the apps (HPA)

### ISSUE THREAD

**Issue by springdo** [rht-labs/tech-exercise#19]
### Advanced deployments
* Module: Autoscaling

### 📝 Description
ArgoCD config to enable hpa in stage or test
Add the HPA yaml to the pet-battle api charts.
Fire some load, watch it scale up / down. 
come up with good metrics to scale on and tweak via argocd override or app change

### 🥤 Additional Info 
hpa for pb is disabled by default. [chart is here](https://github.com/rht-labs/pet-battle-api/blob/main/chart/templates/hpa.yaml)

### ✅ A/Cs
- [x] Big Picture Updated (if applicable)  
- [ ] Facilitator notes updated (if applicable)
- [x] Exercise peer reviewed / tested with one other region member
- [x] Addition of new exercise does not affect previous exercise (maintain modularity)

**Comment by eformat** [comment]
LGTM
