### ISSUE TITLE
🐛 [bug] - `Secure Shell (ssh) Port Exposed in Image` policy is not listed in StackRox(ACS)

### ISSUE THREAD

**Issue by rmarting** [rht-labs/tech-exercise#193]
### 📝 Description

The step 5 of the [Image security](https://rht-labs.com/tech-exercise/#/3-revenge-of-the-automated-testing/7-image-security) exercise describes how to find the `Secure Shell (ssh) Port exposed in Image` policy, however that policy is not listed in my fresh OCP cluster.

This screenshot is evidence that that policy is not included in the Platform Configuration.

![image](https://user-images.githubusercontent.com/8723668/179203411-90532485-2245-4add-b832-01a03e5d6c2c.png)

### 🚶 Steps to reproduce

Just follow the instructions.

### 🧙‍♀️ Suggested solution
... if applicable

**Comment by eformat** [comment]
As per the instructions, you need to 

> Type in Policy

and then 

> Secure Shell (ssh) Port Exposed

![Screenshot from 2022-07-16 11-19-33](https://user-images.githubusercontent.com/712608/179328893-d946044c-d9f9-4765-8493-d7bb24864771.png)

I just tried on latest 4.10 in RHPDS .. works fine.

![Screenshot from 2022-07-16 11-18-45](https://user-images.githubusercontent.com/712608/179328881-3f4ddf31-afa6-40c6-a545-61ea8d076ecf.png)

Closing for now unless you think this is in Error?

**Comment by rmarting** [comment]
OMG! You are rigth @eformat! As I didn't read carefully the instructions ... I couldn't find it successfully (maybe a side effect of the heatwave we are suffering right now). Thank you so much! It was not a bug ...
