### ISSUE TITLE
👑 [exercise] - Blue/Green Deployments

### ISSUE THREAD

**Issue by ckavili** [rht-labs/tech-exercise#20]
### Advanced Deployments
* Module: Blue/Green Deployments

### 📝 Description
Introduce Blue/Green deployment for pet-battle-api. 
Update pipelines (Jenkins & Tekton) and pet-battle helm charts accordingly.
Run the pipeline and see it switches the traffic (from blue to green) after the green one passes the tests.

### 🥤 Additional Info 
suggested blue/green approach for pipeline (swapping labels from active/ inactive once smoke test has been successful)
![image](https://user-images.githubusercontent.com/6122439/128341537-7e505aa5-46cd-4df5-b134-173f084df5dd.png)

### ✅ A/Cs
- [x] Big Picture Updated (if applicable)  
- [ ] Facilitator notes updated (if applicable)
- [x] Exercise peer reviewed / tested with one other region member
- [x] Addition of new exercise does not affect previous exercise (maintain modularity)

**Comment by eformat** [comment]
LGTM
