### ISSUE TITLE
👑 [exercise] - A/B deployment

### ISSUE THREAD

**Issue by springdo** [rht-labs/tech-exercise#21]
### Advanced Deployment
* Module: A/B Deployment

### 📝 Description
Simulate an A/B deployment for the frontend. Update the pet-battle applications with Matomo chart and update the frontend overwrites to point to this new instance. Update arogcd config to house an a and b deployment for the front end. configure the weights using config as code. Show results of experiment in the matomo ui.

### 🥤 Additional Info 
matomo lives [here](https://github.com/petbattle/pet-battle-analytics/tree/main/charts/matomo)
pb-config change is [here](https://github.com/rht-labs/pet-battle/blob/main/chart/values.yaml#L18)

### ✅ A/Cs
- [x] Big Picture Updated (if applicable)  
- [x] Facilitator notes updated (if applicable)
- [x] Exercise peer reviewed / tested with one other region member
- [x] Addition of new exercise does not affect previous exercise (maintain modularity)

**Comment by eformat** [comment]
LGTM
