### ISSUE TITLE
🐛 [bug] - error in link documentation

### ISSUE THREAD

**Issue by lboubeta** [rht-labs/tech-exercise#219]
### 📝 Description

The link provided to install Allure goes to other site.

### 🚶 Steps to reproduce

Click the link in "head over here" and goes to https://rht-labs.com/#/3-revenge-of-the-automated-testing/2b-tekton?id=part-1-allure

### 🧙‍♀️ Suggested solution

The problem is that GitHub pages don't get the "tech-exercise" context after the root domain.

**Comment by ckavili** [comment]
Hey @lboubeta thanks for the heads up!! ☺️ we just updated the link so it's now going to the Allure section of the exercise!
