### ISSUE TITLE
🐛 [bug] - Add Syntax highlighting (prism or highlightjs) to the `<pre></pre>` blocks

### ISSUE THREAD

**Issue by springdo** [rht-labs/tech-exercise#23]
### 📝 Description
The `<pre></pre>` blocks in the markdown are not syntax highlighted. They should be to make it easier for the learner to see what need changing

### 🚶 Steps to reproduce
... if applicable

### 🧙‍♀️ Suggested solution
Look into prism or highlightjs. I know Docsify loads `prismjs` so perhaps we could / should be able to use it without if affecting the copy plugin....

**Comment by ckavili** [comment]
I tried with `prismjs` and updated the docs. For example, check the 3rd step in this chapter: https://rht-labs.com/tech-exercise/#/1-the-manual-menace/5-this-is-gitops ..not perfect, but better than before I think :)

**Comment by springdo** [comment]
That's great @ckavili ! Thanks 👍
