### ISSUE TITLE
👑 [exercise] - A New Group

### ISSUE THREAD

**Issue by rmarting** [rht-labs/tech-exercise#246]
### A New Group
* Module: A New Group

### 📝 Description

This exercise summarizes the main steps to create a new group (hope) inside a formed team. The first exercises create the initial structures, and repositories, needed to continue other exercises. If a new group (hope), mostly a new pair, wants to work then it is needed to create a new CRW environment, and setup some initial activities (e.g. clone the created repos in Gitlab).

The current content includes the steps to setup from the scratch an CRW environment, but not how to onboard into already created team. There are some dispersed notes along the content, but not in a central manner.

It could be great to have an additional exercise to help the teams to split into more groups and set up easily the new CRW environments and accelerate their delivery life cycle.

### 🥤 Additional Info 

It is proposed to created an additional exercise, at the end of the technical exercises to summarize all these steps. For example, we could call it **A New Group** (following the sequence of `A New Hope` films)

### ✅ A/Cs
- [ ] Big Picture Updated (if applicable)  
- [ ] Facilitator notes updated (if applicable)
- [ ] Exercise peer reviewed / tested with one other region member
- [X] Addition of new exercise does not affect previous exercise (maintain modularity)

**Comment by ckavili** [comment]
thanks for the contribution https://github.com/rht-labs/tech-exercise/pull/247 @rmarting 🎸 🤘 closing the issue now 😇
