### ISSUE TITLE
🐛 [bug] - Unable to deploy ArgoCD in exercise 1 - RBAC errors

### ISSUE THREAD

**Issue by rmarting** [rht-labs/tech-exercise#25]
### 📝 Description

Following instrucctions of Exercise 1 to deploy ArgoCD I found an exception related with RBAC policies for my user.

```text
Error: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource: clusterrolebindings.rbac.authorization.k8s.io "team8-ci-cd-argocd-application-controller" is forbidden: User "team8" cannot get resource "clusterrolebindings" in API group "rbac.authorization.k8s.io" at the cluster scope
```

### 🚶 Steps to reproduce

Output of the command with the error:

```shell
sh-4.4$ helm upgrade --install argocd \
>   --namespace ${TEAM_NAME}-ci-cd \
>   -f /projects/tech-exercise/argocd-values.yaml \
>   redhat-cop/argocd-operator
Release "argocd" does not exist. Installing it now.
Error: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource: clusterrolebindings.rbac.authorization.k8s.io "team8-ci-cd-argocd-application-controller" is forbidden: User "team8" cannot get resource "clusterrolebindings" in API group "rbac.authorization.k8s.io" at the cluster scope
```

This is a OCP 4.6 cluster deployed automatically by LodeStar, as part of a coming DO500 Enablement, and I am connected using a developer user (e.g: team8) with the default capabilities of a DO500 developer user.

Should my user has more capabilities? Is it missed something in the cluster to execute this step?

**Comment by eformat** [comment]
hi @rmarting, try this step (part of deploying do500 helm chart, not yet automated):
```
oc apply -f https://raw.githubusercontent.com/rht-labs/enablement-framework/main/do500-rbac.yaml
```

**Comment by rmarting** [comment]
As my current OCP 4.6 was already provisoned by LodeStar, and I am starting an enablement today ... do you know if there is any conflict of those charts with my current OCP? I don't want to destroy anything already running successfully for the attendees. In the afternoon I am testing this new version, on the same cluster, if there is not conflict.

I guess to execute these helm charts I need to be `cluster-admin`, right?

thanks

**Comment by eformat** [comment]
Hi .. probably best to discuss the details in gchat. This is the new tech exercise content. Don't think there was any intention on running both side by side, certainly not something we have tested. Yes, you need cluster admin privilege. Closing this for now.
