### ISSUE TITLE
🐛 [bug] - Tekton step deploy-test fails

### ISSUE THREAD

**Issue by lieberlois** [rht-labs/tech-exercise#290]
### 📝 Description
I strictly followed the workshop from the KCD conference today. The Tekton Pipeline fails with the following issue:

```bash
STEP-GET-CURRENT-INFO

2024/07/01 14:52:52 warning: unsuccessful cred copy: ".docker" from "/tekton/creds" to "/": unable to create destination directory: mkdir /.docker: permission denied
2024/07/01 14:52:52 warning: unsuccessful cred copy: ".gitconfig" from "/tekton/creds" to "/": unable to open destination: open /.gitconfig: permission denied
2024/07/01 14:52:52 warning: unsuccessful cred copy: ".git-credentials" from "/tekton/creds" to "/": unable to open destination: open /.git-credentials: permission denied
Error: yaml: line 23: could not find expected ':'
STEP-PATCH-ARGO-CONF

2024/07/01 14:52:52 warning: unsuccessful cred copy: ".docker" from "/tekton/creds" to "/": unable to create destination directory: mkdir /.docker: permission denied
2024/07/01 14:52:52 warning: unsuccessful cred copy: ".gitconfig" from "/tekton/creds" to "/": unable to open destination: open /.gitconfig: permission denied
2024/07/01 14:52:52 warning: unsuccessful cred copy: ".git-credentials" from "/tekton/creds" to "/": unable to open destination: open /.git-credentials: permission denied
2024/07/01 14:52:56 Skipping step because a previous step failed
STEP-COMMIT-CHANGES

2024/07/01 14:52:57 Skipping step because a previous step failed
```

### 🚶 Steps to reproduce
Follow the instructions at https://petbattle.github.io/gitops-workshop/#/2-attack-of-the-pipelines/3-the-pipelines

### 🧙‍♀️ Suggested solution
Provide guidance to fix this

**Comment by lieberlois** [comment]
<img width="1221" alt="image" src="https://github.com/rht-labs/tech-exercise/assets/25712873/6d26860b-56b9-449b-a4de-faba6f732618">

**Comment by ckavili** [comment]
hey @lieberlois. Thanks for the issue! there is a chance there is a typo in GitOps config under `tech-exercise/pet-battle/test/values.yaml` file. Would you mind to check that one please? 🙏

**Comment by lieberlois** [comment]
Oh my gawd, it was in fact a newline character that was accidentally copied. Thank you so much! 🥳 Great session, I wish we would have had more time 👍

**Comment by ckavili** [comment]
by the way, if Argo CD is unhappy after you fixed that typo, I suggest you update the version to something like `1.3.3` and trigger the pipeline again. Because Nexus probably is not set up to overwrite the helm package if you are pushing the chart without changing the version. 
(for the convenience, we alight application version with the helm chart version here🙈)

just run:
```
cd /projects/pet-battle-api
mvn -ntp versions:set -DnewVersion=1.3.3
```

hope it helps ❤️

**Comment by lieberlois** [comment]
@ckavili Yeah I had to make some more adjustments but eventually got it to work ☺️ thx
