### ISSUE TITLE
🖹 [slides] - Scrum Framework (and ceremonies)

### ISSUE THREAD

**Issue by rmarting** [rht-labs/tech-exercise#41]
### SCRUM
* Module: SCRUM

### 📝 Description

Scrum Framework to acelerate delivery loop. This practice could cover the following entries in the content loop:

- Sprint Planning
- Daily Standup
- Showcase

It could be great to add a new image in the content loop for Scrum, as there is already for Kanban

### 🥤 Additional Info 
...link to the docs where the slides content should be added or links to blogs etc that form the basis of the content.

* [Slides](https://rht-labs.com/tech-exercise/slides/content/?name=scrum)
* [OPL - Sprint Planning](https://openpracticelibrary.com/practice/iteration-planning/)
* [OPL - Daily Standup](https://openpracticelibrary.com/practice/daily-standup/)
* [OPL - Showcase](https://openpracticelibrary.com/practice/showcase/)

### ✅ A/Cs
- [ ] Content
- [ ] Facilitator notes updated (if applicable)
- [ ] Slides content peer reviewed with one other region member
- [ ] Content loop image updated (if applicable)
- [ ] Slides content linked in content loop image

**Comment by ckavili** [comment]
done https://rht-labs.com/tech-exercise/slides/content/?name=scrum 👍
