### ISSUE TITLE
🖹 [slides] - Non-Functional Requirements Map

### ISSUE THREAD

**Issue by rmarting** [rht-labs/tech-exercise#44]
### Non-Functional Requirements Map
* Module: Non-Functional Requirements Map

### 📝 Description

Non-Functional Requirements Map - A collaborative approach for capturing non-functional requirements

### 🥤 Additional Info 
...link to the docs where the slides content should be added or links to blogs etc that form the basis of the content.

* [OPL - Non-Functional Requirements Map](https://openpracticelibrary.com/practice/non-functional-requirements-map/)

### ✅ A/Cs
- [x] Content
- [x] Facilitator notes updated (if applicable)
- [x] Slides content peer reviewed with one other region member
- [x] Content loop image updated (if applicable)
- [x] Slides content linked in content loop image

**Comment by ckavili** [comment]
done - https://rht-labs.com/tech-exercise/slides/content/?name=non-functional-map :)
