### ISSUE TITLE
🖹 [slides] - Big Picture

### ISSUE THREAD

**Issue by rmarting** [rht-labs/tech-exercise#47]
### Big Picture
* Module: Big Picture

### 📝 Description

Big Picture

### 🥤 Additional Info 
...link to the docs where the slides content should be added or links to blogs etc that form the basis of the content.

### ✅ A/Cs
- [ ] Content
- [ ] Facilitator notes updated (if applicable)
- [ ] Slides content peer reviewed with one other region member
- [ ] Content loop image updated (if applicable)
- [ ] Slides content linked in content loop image

**Comment by ckavili** [comment]
There is no separate Big Picture practice section but every tech exercise has a Big Picture on the first page (like https://rht-labs.com/tech-exercise/#/1-the-manual-menace/README) and we have those Big Pictures in tech related slides as well 🙂 if we feel we need a separate section/module, let's capture it with a separate issue - thanks!
