### ISSUE TITLE
🐛 [bug] - pet-battle Jenkins pipeline is not created

### ISSUE THREAD

**Issue by rmarting** [rht-labs/tech-exercise#57]
### 📝 Description

Following the instructions described [here](https://rht-labs.com/tech-exercise/#/2-attack-of-the-pipelines/3a-jenkins) to create the Jenkins pipeline of the pet-battle application, I cannot get the new pipeline be created.

I executed the `seed-multibranch-pipelines` pipeline manually, the following exceptions are showed in the Jenkins' pod logs:

```
2021-11-29 07:52:02 WARNING hudson.model.listeners.RunListener report RunListener failed
java.lang.NoClassDefFoundError: org/junit/rules/ExternalResource
	at org.jvnet.hudson.test.BuildWatcher$Listener.onStarted(BuildWatcher.java:89)
	at hudson.model.listeners.RunListener.fireStarted(RunListener.java:237)
	at hudson.model.Run.execute(Run.java:1886)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:99)
	at hudson.model.Executor.run(Executor.java:431)
```

### 🚶 Steps to reproduce
Basically follow the instructions of the technical exercise. This is a blocker to follow other exercises using Jenkins, instead of Tekton.

**Comment by ckavili** [comment]
hey @rmarting are you still experiencing this issue? If yes, would you please share your Jenkins env values and git repo config? thanks.

**Comment by rmarting** [comment]
At this moment I don't have the environment where I found this issue. I should try again in a new environment to confirm if this is a real issue with the tech exercise or something related with my previous environment. In January I will take some time to repeat and come back here with more details.

**Comment by rmarting** [comment]
After some research from @ckavili, we found the root cause of this issue: the pet-battle repo was created as private, instead of public as the doc says [here](https://rht-labs.com/tech-exercise/#/2-attack-of-the-pipelines/3a-jenkins):

```
1. Open the GitLab UI. Create a repo in GitLab under rmarting-tl500 group called pet-battle. Make the project as public.
```

So this is not a real issue. Closing it!
