### ISSUE TITLE
👑 [exercise] - Sonar Scanning

### ISSUE THREAD

**Issue by springdo** [rht-labs/tech-exercise#6]
### Quality Gates Exercise
* Module: Sonar-scanning

### 📝 Description
Add sonar scanning for the application code quality. This should run independently of any other Quality Gate module in order to maintain executing the exercise in any order.

### 🥤 placeholder 
https://github.com/rht-labs/tech-exercise/blob/main/docs/3-revenge-of-the-automated-testing/1-sonar-scanning.md

### ✅ A/Cs
- [x] Big Picture Updated (if applicable)  
- [x] Exercise peer reviewed / tested with one other region member
- [x] Addition of new exercise does not affect previous exercise (maintain modularity)

**Comment by rmarting** [comment]
Reviewing Tekton pipeline to analyze the code I found the next error:

```text
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  18.111 s
[INFO] Finished at: 2021-11-23T10:23:18Z
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'sonar' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/workspace/maven-m2/.m2/repository), maven-public (http://nexus:8081/repository/maven-public/)] -> [Help 1]
[ERROR] 
```

The root cause of this issue is because sonar-maven-plugin is not in the `pom.xml` file of `pet-battle-api` project. In that case if you want to execute the plugin you need to use the full path to the goal `org.sonarsource.scanner.maven:sonar-maven-plugin:sonar` in the `maven-pipeline.yaml` file:

```yaml
      params:
        - name: WORK_DIRECTORY
          value: "$(params.APPLICATION_NAME)/$(params.GIT_BRANCH)"
        - name: GOALS
          value: "test org.sonarsource.scanner.maven:sonar-maven-plugin:sonar"  # - org.owasp:dependency-check-maven:check
        - name: MAVEN_BUILD_OPTS
          value: "-Dsonar.host.url=http://sonarqube-sonarqube:9000 -Dsonar.userHome=/tmp/sonar"
```

With that value it works. Other option could be add the maven plugin sonar in the `pom.xml` file:

```xml
      <plugin>
        <groupId>org.sonarsource.scanner.maven</groupId>
        <artifactId>sonar-maven-plugin</artifactId>
        <version>3.7.0.1746</version>
      </plugin>
```

Reference: https://docs.sonarqube.org/latest/analysis/scan/sonarscanner-for-maven/

**Comment by eformat** [comment]
@rmarting have you got some details on how this is running ?
it has not been a problem for the mvn sonar:sonar target to date. maven will use the latest version of the plugin if it is not specified and pull that via nexus from maven central.
here is a screenshot of it working:

![Screenshot from 2021-11-24 07-56-52](https://user-images.githubusercontent.com/712608/143135583-7f2393e1-b43a-481f-8180-66138967ad97.png)

**Comment by rmarting** [comment]
Sorry @eformat you are right but it seems that my issue was related with other thing ... Nexus is not working successfully, with many restarts that do not allow to download all the artifacts on time. 

After some retries it worked successfully with the same ouput.

Reverted my PR with that change.
