### ISSUE TITLE
🐛 [bug] - My user doesn't have privileges to see the ${TEAM_NAME}-(stage|test) namespaces

### ISSUE THREAD

**Issue by alexpdp7** [rht-labs/tech-exercise#62]
### 📝 Description

I can't access namespaces that the exercise creates.

### 🚶 Steps to reproduce

Follow the https://rht-labs.com/tech-exercise/#/2-attack-of-the-pipelines/2-app-of-apps exercise up to step 6.

This apparently creates two namespaces ( ${TEAM_NAME}-(stage|test) ), but my OCP user does not seem to be able to access those, so I cannot follow subsequent steps.

`oc get project`, the console, etc. do not show those projects/namespaces.

### 🧙‍♀️ Suggested solution

Grant privileges to users?

**Comment by eformat** [comment]
OK, i tested this out, LGTM .. basically the wrong group hardcoded in docs.
i don't think we need to make this changeable as once lodestar deploys, it will stay as "lodestar-developers"

@alexpdp7 - can you update your values-tooling.yaml in git with this

https://github.com/rht-labs/tech-exercise/commit/ee2b3cb886c3c634caa55889ea463cd3a31be32a

 argo should do the rest !

**Comment by alexpdp7** [comment]
Yeah, that works. My test pet-battle website is borked, but I believe that's unrelated to this problem.

You may close this issue.

**Comment by eformat** [comment]
Awesome thanks @alexpdp7
