### ISSUE TITLE
🐛 [bug] - Instructions to edit `CatResource.java` don't line up

### ISSUE THREAD

**Issue by alexpdp7** [rht-labs/tech-exercise#69]
### 📝 Description

Step 5 of https://rht-labs.com/tech-exercise/#/3-revenge-of-the-automated-testing/4b-tekton doesn't seem to make sense.

### 🚶 Steps to reproduce

Try to execute that step. I assume it's refering to this piece of code:

https://github.com/rht-labs/pet-battle-api/blob/a500577373ec540fb1787c663e9fa0103cd397bc/src/main/java/app/petbattle/CatResource.java#L249

but there is no comment to remove.

### 🧙‍♀️ Suggested solution

Maybe replace the `printStackTrace` method call with a comment?

**Comment by eformat** [comment]
OK couple of changes to fix this

# helper in the code
https://github.com/rht-labs/pet-battle-api/commit/2f5276096749a80cda993139e85d73c73562d27e

# new screenshots before and after
https://github.com/rht-labs/tech-exercise/commit/d966132a225e0ba08e179f72388ebf992f721cec

**Comment by alexpdp7** [comment]
https://rht-labs.com/tech-exercise/#/3-revenge-of-the-automated-testing/4b-tekton now looks good to me, so I'm good with closing this.

**Comment by eformat** [comment]
cheers !
