### ISSUE TITLE
🐛 [bug] - Logging Kibana/ES not available 

### ISSUE THREAD

**Issue by eformat** [rht-labs/tech-exercise#79]
Kibana/ES not available for

http://localhost:3000/#/4-return-of-the-monitoring/3-logging?id=aggregated-logging

this bug is tracking https://github.com/rht-labs/enablement-framework/pull/76

**Comment by alexpdp7** [comment]
This seems to be working now, I'm OK to close this.

**Comment by eformat** [comment]
thanks @alexpdp7 !
