### ISSUE TITLE
🐛 [bug] - Grafana fails to install

### ISSUE THREAD

**Issue by alexpdp7** [rht-labs/tech-exercise#82]
### 📝 Description

Grafana fails to install

### 🚶 Steps to reproduce

https://rht-labs.com/tech-exercise/#/4-return-of-the-monitoring/1-enable-monitoring

run until step 3, then Argo reports sync failed.

![image](https://user-images.githubusercontent.com/1150630/147083902-1998d17b-1635-435c-83e1-91f02bb9206f.png)

![image](https://user-images.githubusercontent.com/1150630/147083931-bf6f76c1-a9dc-4ed0-bb0f-2d948203113e.png)

**Comment by alexpdp7** [comment]
This seems to have been fixed. I'm OK with closing this.

**Comment by ckavili** [comment]
awesome :)
