### ISSUE TITLE
👑 [exercise] - StackRox

### ISSUE THREAD

**Issue by ckavili** [rht-labs/tech-exercise#9]
### Quality Gates
* Module: StackRox

### 📝 Description
Introduce StackRox for container and hist security for front end and API (Jenkins & Tekton)

### 🥤 Additional Info 
Docs:
[StackRox - General Info](https://github.com/rht-labs/tech-exercise/blob/main/docs/3-revenge-of-the-automated-testing/6-stack-rox.md)
[Jenkins](https://github.com/rht-labs/tech-exercise/blob/main/docs/3-revenge-of-the-automated-testing/6a-jenkins.md)
[Tekton](https://github.com/rht-labs/tech-exercise/blob/main/docs/3-revenge-of-the-automated-testing/6b-tekton.md)

### ✅ A/Cs
- [x] Big Picture Updated (if applicable)  
- [x] Facilitator notes updated (if applicable)
- [ ] Exercise peer reviewed / tested with one other region member
- [x] Addition of new exercise does not affect previous exercise (maintain modularity)

**Comment by eformat** [comment]
i have been investigating this ... pushed some docs for initial stuff .. ACM/StackRox .. is impressive

**Comment by ckavili** [comment]
Exercise peer reviewed. A separate issue regarding vulnerabilities tracking here https://github.com/rht-labs/tech-exercise/issues/72 Closing this one
